load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "murmur_hash",
    srcs = ["MurmurHash3.cpp"],
    hdrs = ["MurmurHash3.h"],
    include_prefix = "flagd/evaluator/murmur_hash",
    strip_include_prefix = "",
    visibility = ["//visibility:public"],
)
