name: ci-format-test-lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel test //providers/...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build
        run: bazel build //...

      - name: Build compilation database
        run: bazel run @hedron_compile_commands//:refresh_all

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "file" # Use .clang-format config file.
          tidy-checks: "" # Use .clang-tidy config file.
          database: "compile_commands.json"
          version: "21"
          extra-args: "--system-headers -fdiagnostics-absolute-paths"

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
